<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <PackageId>CorePoints.ApiGateway</PackageId>
    <Description>CorePoints shared library - API Gateway patterns (versioning, Swagger, middleware, exception handling)</Description>
    <Authors>eadelungue</Authors>
    <RepositoryUrl>https://github.com/eadelungue/corepoints-shared-libraries</RepositoryUrl>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.*" />
    <PackageReference Include="Asp.Versioning.Http" Version="8.1.*" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.*" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.*" />
  </ItemGroup>

</Project>
